In [ ]:
# Index, slicing, and iteration

In [1]:
import numpy as np

Access to matrix trow indexes

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix[0][0] # 1

1

numpy has a feature that allows you to access the indexes of the rows of a matrix.

In [10]:
matrix[0, 0] # 1

1

Sub matrixes can be accessed by using the indexes of the rows of the matrix.

In [13]:
matrix[0:2, 0:1]

array([[1],
       [4]])

In [15]:
# chose the first column
matrix[0, :]

array([1, 2, 3])

In [17]:
# chose the first row
matrix[:, 0]

array([1, 4, 7])

In [18]:
#max of the matrix
matrix.max()

9

In [19]:
# max by rows
matrix.max(axis=1)

array([3, 6, 9])

In [20]:
# max by columns
matrix.max(axis=0)

array([7, 8, 9])

In [21]:
# min of the matrix
matrix.min()

# min by rows
matrix.min(axis=1)

# min by columns
matrix.min(axis=0)

array([1, 2, 3])

In [22]:
# mean of the matrix
matrix.mean()

5.0

In [23]:
# mean by rows
matrix.mean(axis=1)

array([2., 5., 8.])

In [24]:
# mean by columns
matrix.mean(axis=0)

array([4., 5., 6.])

In [25]:
# standard deviation of the matrix
matrix.std()

2.581988897471611

In [26]:
# standard deviation by rows
matrix.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [27]:
# standard deviation by columns
matrix.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])