In [ ]:
# Index, slicing, and iteration

In [1]:
import numpy as np

Access to matrix trow indexes

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix[0][0] # 1

1

numpy has a feature that allows you to access the indexes of the rows of a matrix.

In [10]:
matrix[0, 0] # 1

1

Sub matrixes can be accessed by using the indexes of the rows of the matrix.

In [13]:
matrix[0:2, 0:1]

array([[1],
       [4]])

In [15]:
# chose the first column
matrix[0, :]

array([1, 2, 3])

In [17]:
# chose the first row
matrix[:, 0]

array([1, 4, 7])