In [2]:
pip install numpy

  Using cached numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

# Create a 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [10]:
# funcion linespace
b = np.linspace(0, 10, 11)
print(b)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [12]:
# funcion arange
c = np.arange(0, 1, 2)
print(c)

[ 0  2  4  6  8 10]


In [13]:
# 2D array
d = np.array([[1, 2, 3], [4, 5, 6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [14]:
# zeros
e = np.zeros((2, 3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# identity matrix
f = np.identity(6)
print(f)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [17]:
# ones matrix
g = np.ones((2, 3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
# sum 2 matrices
h = np.array([[1, 2], [3, 4]])
i = np.array([[5, 6], [7, 8]])
j = h + i
print(j)

[[ 6  8]
 [10 12]]


In [19]:
# substract 2 matrices
k = h - i
print(k)

[[-4 -4]
 [-4 -4]]


In [20]:
# power of a matrix
l = h ** 2
print(l)

[[ 1  4]
 [ 9 16]]
