In [21]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [22]:
import numpy as np

In [23]:
# random matrix of 3x3
matrix = np.random.rand(3,3)
print(matrix)

[[0.56828138 0.04344035 0.4854844 ]
 [0.5799739  0.82444165 0.91792321]
 [0.49756154 0.19039866 0.9000705 ]]


In [27]:
# reshape matrix to 1x9
array = np.random.rand(6)
print(array)

[0.55222691 0.01819239 0.37881495 0.15729544 0.12088189 0.86287951]


In [29]:
array = array.reshape(2,3)
print(array)

[[0.55222691 0.01819239 0.37881495]
 [0.15729544 0.12088189 0.86287951]]


In [34]:
# randint
array = np.random.randint(10, size=(3,3))
print(array)

[[8 0 0]
 [4 6 2]
 [5 5 9]]
